name: time_machine
description: Date and time library for Flutter, Web, and Server with support for timezones, calendars, cultures, formatting and parsing.
version: 0.8.0
homepage: https://github.com/Dana-Ferguson/time_machine
author: Dana Ferguson <email@example.com>

environment:
  sdk: '>=2.0.0-dev.61.0 <3.0.0'

dependencies:
  meta: "^1.1.5"
  quiver_hashcode: "^1.0.0"
  collection: "^1.14.10"
  resource: "^2.1.4"

dev_dependencies:
  test: "^1.2.0"
  matcher: "^0.12.3"
