name: time_machine
description: Time and date library.
version: 0.0.2
homepage: https://github.com/Joshua-Ferguson/time_machine
author: Dana Ferguson <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  meta: "^1.1.2"
  intl: "^0.15.2"
  logging: "^0.11.3+1"
  quiver_hashcode: "^1.0.0"
  collection: "^1.14.5"

dev_dependencies:
  test: ^0.12.0
  matcher: "^0.12.1+4"
