name: time_machine
description: Date and time library for DartVM, Dart4Web and Flutter with support for timezones, calendars, culture-aware formatting and parsing.
version: 0.3.0
homepage: https://github.com/Joshua-Ferguson/time_machine
author: Dana Ferguson <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'
#  sdk: '>=2.0.0-dev.17.0'

dependencies:
  meta: "^1.1.2"
  quiver_hashcode: "^1.0.0"
  collection: "^1.14.5"
  resource: "^2.1.2"
#  resource: "^2.1.4"

dev_dependencies:
  test: ^0.12.0
  matcher: "^0.12.1+4"
