name: time_machine
description: Date and time library for Flutter, Web, and Server with support for timezones, calendars, cultures, formatting and parsing.
version: 0.7.1
homepage: https://github.com/Dana-Ferguson/time_machine
author: Dana Ferguson <email@example.com>

# Commented out items are for using with Dart 2.0

environment:
  sdk: '>=1.20.1 <2.0.0'
#  sdk: '>=2.0.0-dev.17.0'

dependencies:
  meta: "^1.1.2"
  quiver_hashcode: "^1.0.0"
  collection: "^1.14.5"
  resource: "^2.1.2"
#  resource: "^2.1.4"

dev_dependencies:
  test: ^0.12.0
  matcher: "^0.12.1+4"
