name: time_machine
description: Date and time library for DartVM and Dart4Web with support for timezones, calendars, culture-aware formatting and parsing.
version: 0.0.4
homepage: https://github.com/Joshua-Ferguson/time_machine
author: Dana Ferguson <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  meta: "^1.1.2"
#  intl: "^0.15.2"
  logging: "^0.11.3+1"
  quiver_hashcode: "^1.0.0"
  collection: "^1.14.5"
# 2.1.4 is available but requires Dart 2.0 (not yet stable)
  resource: "^2.1.2"

dev_dependencies:
  test: ^0.12.0
  matcher: "^0.12.1+4"
